sudo: required

services:
  - docker

language: csharp
mono: none
dotnet: 3.0
script:
 - dotnet restore

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
  - docker build -t sitedigitalstore:latest .;
  - docker push "$DOCKER_USER"/sitedigitalstore:latest;