sudo: required


services:
  - docker

language: csharp
mono: none
dotnet: 3.0
script:
 - dotnet restore

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
  - docker build -t diablodoc/digitalsite:v1 .;
  - docker push "$DOCKER_USER"/digitalsite:v1;
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
deploy:
    provider: heroku
    api_key:
        secure: 4ca6c71f-9bc4-408b-8641-72df4eef0310
    app: "$HEROKU_APP_NAME"
    on:
        branch: master
    heroku stack:set heroku-18    